# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 634)
        MainWindow.setMinimumSize(QtCore.QSize(900, 500))
        MainWindow.setStyleSheet("background-color: rgb(56, 58, 89);    \n"
"color: rgb(220, 220, 220);\n"
"border-radius: 10px;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background:none;\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgb(88, 91, 140);\n"
"color: rgb(53, 55, 85);\n"
"border-radius: 10px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255,255,255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 4, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 5, 0, 1, 2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:none;")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background:none;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setMaximumSize(QtCore.QSize(114, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_7.addWidget(self.pushButton_22)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.gridLayout_2.addWidget(self.frame_2, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 4, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_21.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_21.setMaximumSize(QtCore.QSize(114, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_2.addWidget(self.pushButton_21, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 2, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 1, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.page_6)
        self.frame_4.setMinimumSize(QtCore.QSize(400, 500))
        self.frame_4.setStyleSheet(" border:2px solid #ffffff;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_7.addWidget(self.pushButton_11, 4, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_7.addWidget(self.pushButton_9, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
" border:none;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_7.addWidget(self.pushButton_10, 3, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_4, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem10, 1, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem11, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_19 = QtWidgets.QPushButton(self.page_10)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_12.addWidget(self.pushButton_19, 8, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.page_10)
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_12.addWidget(self.listWidget, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.page_10)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.page_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_3.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_3.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_3.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_3.addWidget(self.label_32)
        self.gridLayout_12.addWidget(self.frame_6, 3, 1, 1, 3)
        self.label_27 = QtWidgets.QLabel(self.page_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_12.addWidget(self.label_27, 2, 1, 1, 2)
        self.stackedWidget.addWidget(self.page_10)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_5 = QtWidgets.QFrame(self.page_7)
        self.frame_5.setMinimumSize(QtCore.QSize(400, 500))
        self.frame_5.setStyleSheet(" border:2px solid #ffffff;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
" border:none;")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 0, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_9.addWidget(self.pushButton_13, 2, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_9.addWidget(self.pushButton_12, 4, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_9.addWidget(self.pushButton_14, 3, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_5, 1, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem12, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem13, 1, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem14, 1, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem15, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_34 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_4.addWidget(self.label_34)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 3, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background:rgb(255, 255, 255)")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 3, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 2)
        self.pushButton_23 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_23.setMinimumSize(QtCore.QSize(232, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_4.addWidget(self.pushButton_23, 5, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 5, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_11)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_37 = QtWidgets.QLabel(self.page_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_5.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.page_11)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_5.addWidget(self.label_38)
        self.gridLayout_13.addLayout(self.horizontalLayout_5, 2, 3, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.page_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_39.setObjectName("label_39")
        self.gridLayout_13.addWidget(self.label_39, 2, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.page_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_13.addWidget(self.pushButton_20, 7, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.page_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_36.setObjectName("label_36")
        self.gridLayout_13.addWidget(self.label_36, 1, 1, 1, 1)
        self.textEdit_5 = QtWidgets.QTextEdit(self.page_11)
        self.textEdit_5.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setStyleSheet("background:rgb(255, 255, 255)")
        self.textEdit_5.setObjectName("textEdit_5")
        self.gridLayout_13.addWidget(self.textEdit_5, 4, 1, 1, 4)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem16, 2, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_35 = QtWidgets.QLabel(self.page_11)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_6.addWidget(self.label_35)
        self.comboBox_2 = QtWidgets.QComboBox(self.page_11)
        self.comboBox_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.gridLayout_13.addLayout(self.horizontalLayout_6, 5, 1, 1, 2)
        self.stackedWidget.addWidget(self.page_11)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.page_4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_12 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_19 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(255,255,255);")
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background:none;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_10 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.spinBox_2 = QtWidgets.QSpinBox(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setStyleSheet("background:none;")
        self.spinBox_2.setMaximum(1000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_11 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.spinBox_3 = QtWidgets.QSpinBox(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setStyleSheet("background:none;")
        self.spinBox_3.setMaximum(1000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_5.setMinimumSize(QtCore.QSize(201, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(114, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton_5)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.page_4)
        self.calendarWidget.setMaximumSize(QtCore.QSize(500, 300))
        self.calendarWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.calendarWidget)
        self.label_20 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(255,255,255);")
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.pushButton_18 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_18.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButton_18.setMaximumSize(QtCore.QSize(114, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_18)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_6.addWidget(self.textEdit_2, 4, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.gridLayout_6.addWidget(self.frame_3, 4, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgb(255,255,255);")
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:rgb(255,255,255);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background:rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_6.setMaximumSize(QtCore.QSize(114, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem18)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_16 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.page_5)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background:none;")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushButton_16 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_16.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_3.addWidget(self.pushButton_16)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_22 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:rgb(255,255,255);")
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_8.setMaximumSize(QtCore.QSize(114, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.gridLayout_6.addLayout(self.verticalLayout, 5, 0, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(255,255,255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 4)
        self.label_21 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_23 = QtWidgets.QLabel(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:rgb(255,255,255);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 0, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:rgb(255,255,255);")
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 2, 0, 1, 1)
        self.textEdit_4 = QtWidgets.QTextEdit(self.page_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout_5.addWidget(self.textEdit_4, 3, 0, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit(self.page_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_5.addWidget(self.textEdit_3, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.page_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 2, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_17.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_17.setMaximumSize(QtCore.QSize(114, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_5.addWidget(self.pushButton_17, 5, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_26 = QtWidgets.QLabel(self.page_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_11.addWidget(self.label_26, 0, 1, 1, 2)
        self.pushButton_15 = QtWidgets.QPushButton(self.page_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_15.setMaximumSize(QtCore.QSize(114, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"background:none;\n"
" border:2px solid #ffffff;\n"
" border-radius:6px;\n"
" color:#ffffff;\n"
" padding-top:3px;\n"
" padding-bottom:3px;\n"
"max-width:110px;\n"
"}\n"
"     QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(195, 206, 224);\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_11.addWidget(self.pushButton_15, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.page_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(88, 91, 140);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout_11.addWidget(self.tableWidget, 2, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_9)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Automated Answer Checker"))
        self.label_9.setText(_translate("MainWindow", "Welcome to Automated Answer Checker"))
        self.pushButton_2.setText(_translate("MainWindow", "Teacher"))
        self.pushButton.setText(_translate("MainWindow", "Student"))
        self.label_4.setText(_translate("MainWindow", "Student Login"))
        self.label_2.setText(_translate("MainWindow", "Student ID"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.pushButton_3.setText(_translate("MainWindow", "Login"))
        self.pushButton_22.setText(_translate("MainWindow", "Sign up"))
        self.pushButton_21.setText(_translate("MainWindow", "<"))
        self.pushButton_11.setText(_translate("MainWindow", "Exit"))
        self.pushButton_9.setText(_translate("MainWindow", "Take Quiz"))
        self.label_17.setText(_translate("MainWindow", "Student Side"))
        self.pushButton_10.setText(_translate("MainWindow", "See Results"))
        self.pushButton_19.setText(_translate("MainWindow", "Start Quiz"))
        self.label_33.setText(_translate("MainWindow", "Avaliable Quiz"))
        self.label_28.setText(_translate("MainWindow", "Quiz Name:"))
        self.label_29.setText(_translate("MainWindow", "Quiz Date:"))
        self.label_30.setText(_translate("MainWindow", "Quiz Avaliable:"))
        self.label_31.setText(_translate("MainWindow", "Total MCQs"))
        self.label_32.setText(_translate("MainWindow", "Total Questions:"))
        self.label_27.setText(_translate("MainWindow", "Quiz Brief"))
        self.label_18.setText(_translate("MainWindow", "Teacher Side"))
        self.pushButton_13.setText(_translate("MainWindow", "Make Quiz"))
        self.pushButton_12.setText(_translate("MainWindow", "Exit"))
        self.pushButton_14.setText(_translate("MainWindow", "See Report"))
        self.label_5.setText(_translate("MainWindow", "Quiz "))
        self.label_8.setText(_translate("MainWindow", "Time:"))
        self.label_34.setText(_translate("MainWindow", "00:00"))
        self.label_6.setText(_translate("MainWindow", "Question: "))
        self.label_7.setText(_translate("MainWindow", "This is a Question"))
        self.pushButton_23.setText(_translate("MainWindow", "Upload Answer From image"))
        self.pushButton_4.setText(_translate("MainWindow", "Next Question"))
        self.label_37.setText(_translate("MainWindow", "Time:"))
        self.label_38.setText(_translate("MainWindow", "00:00"))
        self.label_39.setText(_translate("MainWindow", "Question: "))
        self.pushButton_20.setText(_translate("MainWindow", "Next Question"))
        self.label_36.setText(_translate("MainWindow", "MCQs"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "Options: "))
        self.label_12.setText(_translate("MainWindow", "Teacher: Name of Teacher"))
        self.label_19.setText(_translate("MainWindow", "Quiz Name:"))
        self.label_10.setText(_translate("MainWindow", "Total MCQs"))
        self.label_11.setText(_translate("MainWindow", "Total Questions"))
        self.pushButton_5.setText(_translate("MainWindow", "Start Adding Questions"))
        self.label_20.setText(_translate("MainWindow", "Date fo the Quiz:"))
        self.pushButton_18.setText(_translate("MainWindow", "<"))
        self.label_14.setText(_translate("MainWindow", "MCQs #"))
        self.label_15.setText(_translate("MainWindow", "Add Options"))
        self.pushButton_6.setText(_translate("MainWindow", "Add Option"))
        self.label_16.setText(_translate("MainWindow", "Added Options"))
        self.pushButton_16.setText(_translate("MainWindow", "Correct Option"))
        self.pushButton_7.setText(_translate("MainWindow", "Delete"))
        self.label_22.setText(_translate("MainWindow", "Correct option:"))
        self.pushButton_8.setText(_translate("MainWindow", "Next Question"))
        self.label_13.setText(_translate("MainWindow", "Adding MCQs"))
        self.label_21.setText(_translate("MainWindow", "Preview"))
        self.label_23.setText(_translate("MainWindow", "Adding Questions"))
        self.label_25.setText(_translate("MainWindow", "Question:"))
        self.label_24.setText(_translate("MainWindow", "Answer:"))
        self.pushButton_17.setText(_translate("MainWindow", "ADD Question"))
        self.label_26.setText(_translate("MainWindow", "Report"))
        self.pushButton_15.setText(_translate("MainWindow", "<"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Student"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quiz"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total Marks"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Obtained Marks"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
